### ISSUE TITLE
jsファイルをディレクトリにまとめる

### ISSUE THREAD

**Issue by orisano** [wassan128/lookat#1]
jsファイルがprojectのルートに展開されてますがどうなんでしょうか.

lookatディレクトリであったり,srcディレクトリであったりにまとめた方がいいんじゃないでしょうか？

**Comment by wassan128** [comment]
ご指摘いただきありがとうございます。
リファクタリング時にルートにファイルを複数作成し、そのままにしていました。

現在はpublic, viewディレクトリを参照するファイル(app.js)以外を全てlookatディレクトリに移してあります。

**Comment by orisano** [comment]
素晴らしい
